# Site settings
name: XY Blog
email: liuxm0315@hotmail.com
author: Xingmin Liu
url: https://liuxm0239.github.io/
#resume_site: http://www.hifreud.com/Resume.io/
github: https://github.com/liuxm0239
baseurl: ""
description: 为学日益，为道日损。
meta_description: 个人博客; What we do not understand we do not possess.
motto: Experience keeps a dear school, but fools will learn in no other.
banner: No Silver Bullet.

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: liuxm0239

# Build settings
markdown: kramdown

#baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

